[package]
name = "dtsfmt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.7.6"
tree-sitter = "0.20.10"

[build-dependencies]
cc="*"
